### PR TITLE
Run CI checks with GitHub workflow

### PR DESCRIPTION
**Pull request by thc202**
Add workflow to run CI checks with GitHub.
Remove Travis CI configuration.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Is the plan to change this to PR (or well pull_request_target) after it's been tested?

**Comment by thc202** [comment]
This was meant to be for PRs already... added the `pull_request` event.

**Comment by kingthorin** [comment]
I think we need to drop push (or add conditionals) and the PR handling needs to checkout the PR branch:
```
with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
```

**Comment by thc202** [comment]
The `push` is to build the merges into main `branch` (having both does not trigger additional builds on PRs).

I don't think it's necessary, the PR is already being checked out:
https://github.com/zaproxy/fuzzdb-offensive/pull/18/checks?check_run_id=1696601194#step:2:366

**Comment by kingthorin** [comment]
Okay, cool, merging.

**Comment by kingthorin** [comment]
Success: https://github.com/zaproxy/fuzzdb-offensive/runs/1696700839?check_suite_focus=true

**Pull request merged**
