### PR TITLE
Update build/workflows, compile with Java 11

### PR DESCRIPTION
**Pull request by thc202**
Update Gradle to 7.5.1, compile the add-on with Java 11.
Update workflows' actions and Java version.

### CODE REVIEW

**Comment by thc202** [comment]
The add-on itself does not have Java code, more for the build.

**Comment by kingthorin** [comment]
I guess if I tackle neonmarker it should look similar to this?

**Comment by thc202** [comment]
Yes.

**Comment by thc202** [comment]
Add missing distribution to two workflows.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
